---
# tasks/main.yml
- name: Download Prometheus tarball
  get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/{{ prometheus_version }}/prometheus-{{ prometheus_version_without_v }}.linux-amd64.tar.gz"
    dest: /tmp/prometheus.tar.gz

- name: Extract Prometheus
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /opt/
    remote_src: yes

- name: Create symbolic link for Prometheus binaries
  file:
    src: "/opt/prometheus-{{ prometheus_version }}.linux-amd64/prometheus"
    dest: "/usr/local/bin/prometheus"
    state: link

- name: Create Prometheus data directory
  file:
    path: /var/lib/prometheus
    state: directory
    owner: prometheus
    group: prometheus

- name: Create Prometheus configuration directory
  file:
    path: /etc/prometheus
    state: directory
    owner: prometheus
    group: prometheus

- name: Copy Prometheus configuration file
  template:
    src: prometheus.yml.j2
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: "0644"

- name: Create Prometheus systemd service file
  copy:
    content: |
      [Unit]
      Description=Prometheus Monitoring
      Wants=network-online.target
      After=network-online.target

      [Service]
      User=prometheus
      Group=prometheus
      Type=simple
      ExecStart=/usr/local/bin/prometheus \
        --config.file=/etc/prometheus/prometheus.yml \
        --storage.tsdb.path=/var/lib/prometheus \
        --web.console.templates=/opt/prometheus-{{ prometheus_version }}.linux-amd64/consoles \
        --web.console.libraries=/opt/prometheus-{{ prometheus_version }}.linux-amd64/console_libraries

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/prometheus.service
    mode: "0644"

- name: Reload systemd daemon
  command: systemctl daemon-reload
  notify: restart prometheus

- name: Enable Prometheus service
  systemd:
    name: prometheus
    enabled: yes

- name: Start Prometheus service
  systemd:
    name: prometheus
    state: started


